import Foundation

/// Contents of the QR the Mac shows (SPEC §7): `leveldeck-pair:` + base64url of a JSON
/// `{ v, agentId, agentName, deviceId, key }`.
///
/// - `agentId` identifies the Mac stably (it also travels in the Bonjour TXT).
/// - `deviceId` is the identity the Mac assigned to this iPhone: it is the PSK identity of the
///   handshake and goes in `hello`.
/// - `key` is the PSK. It is the only secret and exists only in the QR and in the two Keychains.
public struct PairingCode: Equatable, Sendable {
    public static let version = 1
    public static let prefix = "leveldeck-pair:"

    public var agentID: String
    public var agentName: String
    public var deviceID: String
    public var key: PresharedKey

    public init(agentID: String, agentName: String, deviceID: String, key: PresharedKey) {
        self.agentID = agentID
        self.agentName = agentName
        self.deviceID = deviceID
        self.key = key
    }

    /// Text for the QR.
    public func encoded() -> String {
        let payload = Payload(v: Self.version, agentId: agentID, agentName: agentName, deviceId: deviceID, key: key)
        // A `Payload` can always be encoded: there are no invalid values.
        let data = (try? ProtocolCoder.encode(payload)) ?? Data()
        return Self.prefix + data.base64URLEncodedString()
    }

    /// Decodes what the camera scanned.
    public init(decoding text: String) throws {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.hasPrefix(Self.prefix) else { throw PairingCodeError.notAPairingCode }
        let body = String(trimmed.dropFirst(Self.prefix.count))
        guard let data = Data(base64URLEncoded: body),
              let payload = try? ProtocolCoder.decode(Payload.self, from: data) else {
            throw PairingCodeError.malformed
        }
        guard payload.v == Self.version else { throw PairingCodeError.unsupportedVersion(payload.v) }
        guard !payload.agentId.isEmpty, !payload.deviceId.isEmpty else { throw PairingCodeError.malformed }
        self.init(agentID: payload.agentId, agentName: payload.agentName, deviceID: payload.deviceId, key: payload.key)
    }

    private struct Payload: Codable {
        var v: Int
        var agentId: String
        var agentName: String
        var deviceId: String
        var key: PresharedKey
    }
}

public enum PairingCodeError: Error, Equatable, Sendable {
    /// The QR is not a LevelDeck one.
    case notAPairingCode
    /// It has the prefix but the contents cannot be understood.
    case malformed
    /// It was generated by a version of the agent this client does not understand.
    case unsupportedVersion(Int)
}
